### DISCUSSION TITLE
e.provide is not a function

### DISCUSSION THREAD

**Discussion by NoxideLive** [TanStack/query#5618] [Q&A]
We are currently in the process of upgrading from Vue 2.6 to Vue 3. In the interim we have upgraded to Vue 2.7 and I have started using Vue Query in the composition API. When running on local dev everything works fine, but when I run a build on our pipeline then the production build cannot run Vue startup. When building locally it does work however. 

The following error is displayed in console and I have attached the network tab when the error is displayed.

```vueQueryPlugin.mjs:90  Uncaught TypeError: e.provide is not a function
    at Object.install (vueQueryPlugin.mjs:90:11)
    at e.use (vue.runtime.esm.js:5785:28)
    at 53188 (main.js:66:1)
    at s (bootstrap:19:32)
    at startup:4:88
    at s.O (chunk loaded:25:12)
    at startup:5:43
    at app.f3245c43.js:1:676944
```
![image](https://github.com/TanStack/query/assets/4605305/89df7d0b-2bc8-4254-8471-a412e8b05a82)

I cannot figure out what I am doing wrong. The code line erroring is `app.provide(clientKey, client);`

Here is the necesarry gitlab-ci.yml

```yml
install dependencies:
  stage: dependencies
  environment: staging

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
  allow_failure: false
  script:
    - echo $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    - cp $PROJECT_ENVIRONMENT_FILE .env
    - npm ci --ignore-scripts
  artifacts:
    paths:
      - .env
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
      - cache/Cypress/
    policy: push

lint:
  stage: lint
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
  script:
    - npm run prod-lint
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull

build for staging:
  stage: deploy staging
  environment: staging
  needs:
    - job: install dependencies
      artifacts: true
    - job: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
  script:
    - cat .env
    - npm run build
  artifacts:
    paths:
      - dist
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
```

package.json

```json
"dependencies": {
    "@ckeditor/ckeditor5-alignment": "^32.0.0",
    "@ckeditor/ckeditor5-autoformat": "^32.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^32.0.0",
    "@ckeditor/ckeditor5-block-quote": "^32.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^28.1.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^28.1.1",
    "@ckeditor/ckeditor5-editor-classic": "^32.0.0",
    "@ckeditor/ckeditor5-essentials": "^32.0.0",
    "@ckeditor/ckeditor5-font": "^32.0.0",
    "@ckeditor/ckeditor5-heading": "^32.0.0",
    "@ckeditor/ckeditor5-indent": "^32.0.0",
    "@ckeditor/ckeditor5-link": "^32.0.0",
    "@ckeditor/ckeditor5-list": "^32.0.0",
    "@ckeditor/ckeditor5-paragraph": "^32.0.0",
    "@ckeditor/ckeditor5-table": "^32.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^32.0.0",
    "@ckeditor/ckeditor5-vue2": "^1.0.5",
    "@ckeditor/ckeditor5-word-count": "^32.0.0",
    "@fullcalendar/core": "^5.8.0",
    "@fullcalendar/daygrid": "^5.8.0",
    "@fullcalendar/interaction": "^5.8.0",
    "@fullcalendar/timegrid": "^5.8.0",
    "@fullcalendar/vue": "^5.8.0",
    "@mdi/font": "^5.9.55",
    "@tanstack/vue-query": "^4.29.11",
    "@vuex-orm/core": "^0.36.3",
    "@vuex-orm/plugin-axios": "^0.9.3",
    "@vuex-orm/plugin-search": "^0.24.1",
    "@wiris/mathtype-ckeditor5": "^7.27.2",
    "axios": "^0.20.0",
    "buefy": "^0.9.19",
    "bulma": "^0.9.3",
    "chart.js": "^3.8.0",
    "chartjs-adapter-date-fns": "^2.0.0",
    "chartjs-plugin-datalabels": "^2.0.0",
    "core-js": "^3.6.5",
    "cypress": "^12.3.0",
    "date-fns": "^2.22.1",
    "dotenv": "^16.0.3",
    "html-loader": "^1.3.2",
    "lodash": "^4.17.20",
    "markdown-loader": "^6.0.0",
    "mixpanel-browser": "^2.45.0",
    "mochawesome": "^7.1.3",
    "moment": "^2.29.4",
    "papaparse": "^5.3.1",
    "perfect-scrollbar": "^1.5.0",
    "postcss": "^8.4.8",
    "postcss-loader": "^4.3.0",
    "raw-loader": "^4.0.2",
    "text-clipper": "^2.1.0",
    "uuid": "^9.0.0",
    "vee-validate": "^3.4.0",
    "vue": "2.7.14",
    "vue-chartjs": "^4.1.1",
    "vue-color": "^2.8.1",
    "vue-cookies": "^1.7.4",
    "vue-croppie": "^2.0.2",
    "vue-debounce": "^3.0.1",
    "vue-emoji-picker": "^1.0.3",
    "vue-i18n": "^8.22.0",
    "vue-infinite-loading": "^2.4.5",
    "vue-router": "^3.5.3",
    "vue-signature-pad": "2.0.5",
    "vue-tel-input": "^5.10.1",
    "vuedraggable": "^2.24.3",
    "vuex": "^3.4.0",
    "vue-demi": "^0.14.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "^5.0.1",
    "@vue/cli-plugin-eslint": "^5.0.1",
    "@vue/cli-plugin-router": "^5.0.1",
    "@vue/cli-plugin-vuex": "^5.0.1",
    "@vue/cli-service": "^5.0.1",
    "eslint": "^8.27.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-vue": "^8.2.0",
    "hosts": "^0.0.1",
    "husky": "^8.0.0",
    "prettier": "2.7.1",
    "sass": "^1.26.12",
    "sass-loader": "^10.0.2",
    "vue-eslint-parser": "^9.1.0",
    "vue-template-compiler": "^2.6.11"
  },
  "peerDependencies": {
    "vue": "^2.7.14"
  },
```
